default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sch_development

test:
  <<: *default
  database: sch_test

production:
  <<: *default
  database: sch_production
